-- CREAR TABLA USUARIO
CREATE TABLE USUARIO (
	IDUSU INTEGER,
	USUUSU VARCHAR2(30),
	PWDUSU VARCHAR2(80),
    NIVUSU INTEGER,
    IDCLI INTEGER,
	ESTUSU CHAR(1),
	CONSTRAINT USUARIO_pk PRIMARY KEY(IDUSU)
);

-- CREAR TABLA CLIENTE
CREATE TABLE CLIENTE (
	IDCLI INTEGER NOT NULL,
	NOMCLI VARCHAR2(50) NOT NULL,
	APECLI VARCHAR2(50) NOT NULL,
	DIRCLI VARCHAR2(80) NOT NULL,
    EMACLI VARCHAR2(50) UNIQUE NOT NULL,
    DNICLI CHAR(8) UNIQUE NOT NULL,
	CELCLI CHAR(9) NOT NULL,
	CODUBI CHAR(6) NOT NULL,
	ESTCLI CHAR(1) NOT NULL,
	CONSTRAINT CLIENTE_pk PRIMARY KEY(IDCLI)
);

-- CREAR TABLA UBIGEO
CREATE TABLE UBIGEO (
    CODUBI CHAR(6) NOT NULL,
    DEPUBI VARCHAR2(50) NOT NULL,
    PROUBI VARCHAR2(50) NOT NULL,
    DISUBI VARCHAR2(50) NOT NULL,
    CONSTRAINT UBIGEO_pk PRIMARY KEY (CODUBI)
);


-- Relacionar la tabla USUARIO - CLIENTE
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_CLIENTE FOREIGN KEY (IDCLI) REFERENCES CLIENTE (IDCLI);
-- Relacionar la tabla CLIENTE - UBIGEO
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_UBIGEO FOREIGN KEY (CODUBI) REFERENCES UBIGEO (CODUBI);


-- CREAR LAS SECUENCIAS
CREATE SEQUENCE ID_USUARIO START WITH 1 INCREMENT BY 1 ORDER;
CREATE SEQUENCE ID_CLIENTE START WITH 1 INCREMENT BY 1 ORDER;


-- CREAR LOS TRIGGERS
CREATE OR REPLACE TRIGGER ID_USUARIO BEFORE INSERT ON USUARIO FOR EACH ROW BEGIN SELECT ID_USUARIO.NEXTVAL INTO :NEW.IDUSU FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER ID_CLIENTE BEFORE INSERT ON CLIENTE FOR EACH ROW BEGIN SELECT ID_CLIENTE.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
END;
/


-- INSERTAR REGISTROS DE UBIGEO
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150501','LIMA','CAÑETE','SAN VICENTE');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150502','LIMA','CAÑETE','ASIA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150503','LIMA','CAÑETE','CALANGO');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150504','LIMA','CAÑETE','CERRO AZUL');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150505','LIMA','CAÑETE','CHILCA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150506','LIMA','CAÑETE','COAYLLO');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150507','LIMA','CAÑETE','IMPERIAL');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150508','LIMA','CAÑETE','LUNAHUANA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150509','LIMA','CAÑETE','MALA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150510','LIMA','CAÑETE','NUEVO IMPERIAL');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150511','LIMA','CAÑETE','PACARAN');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150512','LIMA','CAÑETE','QUILMANA');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150513','LIMA','CAÑETE','SAN ANTONIO');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150514','LIMA','CAÑETE','SAN LUIS');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150515','LIMA','CAÑETE','SANTA CRUZ DE FLORES');
INSERT INTO UBIGEO (CODUBI,DEPUBI,PROUBI,DISUBI) VALUES ('150516','LIMA','CAÑETE','ZUÑIGA');

-- INSERTAR REGISTROS DE CLIENTE
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Juan Gabriel','Condori Jara','Nuevo Hualcara Mz:K Lt:3','juan.condori.jara@vallegrande.edu.pe','70335061','940460321','150501','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Sergio Danilo','Flores Tadeo','San Vicente Mz:J Lt:5','juangabrielcondorijara@gmail.com','50398574','948695767','150502','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Josue Miguel','Alarcon Asto','Santa Rosa Mz:T Lt:7','josue@gmail.com','48947854','998475645','150503','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Maria Daniela','Díaz Romero','Imperial Mz:C Lt:9','maria@gmail.com','49589432','903489256','150504','A');
INSERT INTO CLIENTE (NOMCLI,APECLI,DIRCLI,EMACLI,DNICLI,CELCLI,CODUBI,ESTCLI) VALUES ('Diego Alvaro','Galvez Quispe','Las Malvinas Mz:V Lt:2','diego@gmail.com','46087689','919803481','150505','A');


-- INSERTAR REGISTROS DE USUARIO
INSERT INTO USUARIO (USUUSU,PWDUSU,NIVUSU,IDCLI,ESTUSU) VALUES ('70335061','12345@ABC','1','1','A');
INSERT INTO USUARIO (USUUSU,PWDUSU,NIVUSU,IDCLI,ESTUSU) VALUES ('50398574','12345@ABC','2','2','A');


-- Vista de todos los Clientes Activos|Inactivos
CREATE VIEW vClienteT
AS
SELECT
	 C.IDCLI AS IDCLI,
     INITCAP(C.NOMCLI) AS NOMCLI,
     INITCAP(C.APECLI) AS APECLI,
     INITCAP(C.DIRCLI) AS DIRCLI,
     C.EMACLI AS EMACLI,
	 C.DNICLI AS DNICLI,
	 C.CELCLI AS CELCLI,
     U.CODUBI AS CODUBI,
	 INITCAP(U.DISUBI) AS DISUBI,
     INITCAP(U.PROUBI) AS PROUBI,
     INITCAP(U.DEPUBI) AS DEPUBI,
     C.ESTCLI AS ESTCLI,
	 ROW_NUMBER() OVER (ORDER BY C.IDCLI DESC) AS ORDEN
FROM 
     CLIENTE C
	 INNER JOIN UBIGEO U ON
	 C.CODUBI = U.CODUBI;
